# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  data_path_service:
    class: AppBundle\Service\DataPathService
    arguments: ["@service_container"]
  distance_service:
    class: AppBundle\Service\DistanceService
    arguments: [ "@doctrine.orm.entity_manager" ]
